language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
    - php: nightly
    - php: 7.1
    - php: 7.2
      env:
      - LINT=true
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
